name: Test App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: maierj/fastlane-action@v3.1.0
        with:
          lane: "test_app"